name: CMake CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        generator: ["Visual Studio 17 2022"]  # Рекомендуется использовать только 2022
        config: [Debug, Release]
        include:
          - generator: "Visual Studio 17 2022"
            platform: "x64"
            vs_version: "17.0"
          # Если очень нужно 2019:
          - generator: "Visual Studio 16 2019"
            platform: "x64"
            vs_version: "16.0"
            runs-on: windows-2019  # Требуется специальный runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: ${{ contains(matrix.generator, '2019') && '14.29' || '14.38' }}
          arch: ${{ matrix.platform }}
          sdk: "10.0.20348.0"  # Укажите нужную версию Windows SDK

      - name: Configure CMake
        run: |
          cmake -B build -S . -G "${{ matrix.generator }}" -A ${{ matrix.platform }}
          
      - name: Build
        run: cmake --build build --config ${{ matrix.config }}
