name: CMake CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    strategy:
      matrix:
        config: [Debug, Release]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1.3

      - name: Configure CMake
        shell: cmd
        run: |
          cmake -B build -S . -G "Visual Studio 17 2022" -A x64
          
      - name: Build
        shell: cmd
        run: |
          cmake --build build --config ${{ matrix.config }} -- /m
