name: CMake CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
        include:
          - generator: "Visual Studio 17 2022"
            platform: "x64"
            toolset: "v143"  # Правильный toolset для VS 2022
            vs_version: "17.0"
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vs-version: ${{ matrix.vs_version }}
          toolset: ${{ matrix.toolset }}
          arch: ${{ matrix.platform }}

      - name: Configure CMake
        run: |
          cmake -B build -S . -G "${{ matrix.generator }}" -A ${{ matrix.platform }} -T ${{ matrix.toolset }}
          
      - name: Build
        run: cmake --build build --config ${{ matrix.config }}
